export const BRANCH_SIGNIN_REQUEST = 'BRANCH_SIGNIN_REQUEST'
export const BRANCH_SIGNIN_SUCCESS = 'BRANCH_SIGNIN_SUCCESS'
export const BRANCH_SIGNIN_FAIL = 'BRANCH_SIGNIN_FAIL'
export const BRANCH_SIGNOUT = 'BRANCH_SIGNOUT'

export const BRANCH_SIGNUP_REQUEST = 'BRANCH_SIGNUP_REQUEST'
export const BRANCH_SIGNUP_SUCCESS = 'BRANCH_SIGNUP_SUCCESS'
export const BRANCH_SIGNUP_FAIL = 'BRANCH_SIGNUP_FAIL'