export const COURIER_ADD_REQUEST = 'COURIER_ADD_REQUEST'
export const COURIER_ADD_SUCCESS = 'COURIER_ADD_SUCCESS'
export const COURIER_ADD_FAIL = 'COURIER_ADD_FAIL'


export const COURIER_FETCH_REQUEST = 'COURIER_FETCH_REQUEST'
export const COURIER_FETCH_SUCCESS = 'COURIER_FETCH_SUCCESS'
export const COURIER_FETCH_FAIL = 'COURIER_FETCH_FAIL'

export const COURIER_STATUS_REQUEST = 'COURIER_STATUS_REQUEST'
export const COURIER_STATUS_SUCCESS = 'COURIER_STATUS_SUCCESS'
export const COURIER_STATUS_FAIL = 'COURIER_STATUS_FAIL'


export const COURIER_ASSIGN_REQUEST = 'COURIER_ASSIGN_REQUEST'
export const COURIER_ASSIGN_SUCCESS = 'COURIER_ASSIGN_SUCCESS'
export const COURIER_ASSIGN_FAIL = 'COURIER_ASSIGN_FAIL'




