export const BRANCH_FETCH_REQUEST = 'BRANCH_FETCH_REQUEST'
export const BRANCH_FETCH_SUCCESS = 'BRANCH_FETCH_SUCCESS'
export const BRANCH_FETCH_FAIL = 'BRANCH_FETCH_FAIL'
export const BRANCH_FETCH_RESET = 'BRANCH_FETCH_RESET'