export const PAYMENT_ADD_REQUEST = 'PAYMENT_ADD_REQUEST'
export const PAYMENT_ADD_SUCCESS = 'PAYMENT_ADD_SUCCESS'
export const PAYMENT_ADD_FAIL = 'PAYMENT_ADD_FAIL'

export const CONFIRM_OTP_REQUEST = 'CONFIRM_OTP_REQUEST'
export const CONFIRM_OTP_SUCCESS = 'CONFIRM_OTP_SUCCESS'
export const CONFIRM_OTP_FAIL = 'CONFIRM_OTP_FAIL'


