export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const COURIERBOY_SIGNIN_REQUEST = 'COURIERBOY_SIGNIN_REQUEST'
export const COURIERBOY_SIGNIN_SUCCESS = 'COURIERBOY_SIGNIN_SUCCESS'
export const COURIERBOY_SIGNIN_FAIL = 'COURIERBOY_SIGNIN_FAIL'
export const COURIERBOY_SIGNOUT = 'COURIERBOY_SIGNOUT'

export const COURIERBOY_SIGNUP_REQUEST = 'COURIERBOY_SIGNUP_REQUEST'
export const COURIERBOY_SIGNUP_SUCCESS = 'COURIERBOY_SIGNUP_SUCCESS'
export const COURIERBOY_SIGNUP_FAIL = 'COURIERBOY_SIGNUP_FAIL'

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL'

